<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.8">
  <POU Name="PRG_TEST" Id="{9526a852-d025-00b3-3835-d026c4e6e28a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	FB_ProfidriveGSM_Test : FB_ProfidriveGSM_Test;
	FB_ProfidriveTelegram1_Test : FB_ProfidriveTelegram1_Test;
	FB_SEW_MoviC_Position_Test :FB_SEW_MoviC_Position_Test;
	FB_SEW_MoviC_Velocity_Test : FB_SEW_MoviC_Velocity_Test;
	FB_SEW_Movisafe_CSSx1a_Test : FB_SEW_Movisafe_CSSx1a_Test;
	FB_Siemens_RcvDp_Test : FB_Siemens_RcvDp_Test;
	FB_Siemens_SendDp_Test : FB_Siemens_SendDp_Test;
	
	fbSystem : FB_System;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbSystem();
TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>